version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    restart: on-failure
    command: [sh, -c, "sqlx database create && sqlx migrate run && ./inv-track"]
  db:
    restart: on-failure
